# Gradle Daemon memory & JVM options
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Parallel execution and build cache
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX and R-class optimization
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin & KMP Settings
kotlin.code.style=official
kotlin.incremental=true
kotlin.native.ignoreDisabledTargets=true

